### ISSUE TITLE
Address allows for symbols

### ISSUE THREAD

**Issue by sopa301** [sopa301/pe#8]
In the UG, it is not mentioned that symbols are accepted, but this is a valid input:

![image.png](https://raw.githubusercontent.com/sopa301/pe/main/files/4aa0bbc8-4ffe-4413-b3d1-0f8a7968f186.png)

**Comment by nus-pe-script** [comment]
# Team's Response
No details provided by team.
# Items for the Tester to Verify
## :question: Issue type

Team chose [`type.DocumentationBug`]
Originally [`type.FunctionalityBug`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

<catcher-end-of-segment><hr>
