### ISSUE TITLE
Links are not updated

### ISSUE THREAD

**Issue by sopa301** [sopa301/pe#9]
Links for the following are not pointing at the correct files:

- Architecture:
Main, MainApp

- UI:
Ui.java, MainWindow, MainWindow.fxml

- Logic component:
Logic.java

- Model component:
Model.java

- Storage component:
Storage.java

 
Developers will be able to access the files with great difficulty by searching the actual repository for the files.

**Comment by nus-se-script** [comment]
# Team's Response
Clicking from the content page for the above mentioned works, clicking the links inside also leads to the below screenshot:

![photo1700405566.jpeg](https://raw.githubusercontent.com/nus-cs2103-AY2324S1/pe/master/files/cef1a967-ecf4-4fb0-b05b-4b4fb5989332.jpeg)
# Items for the Tester to Verify
## :question: Issue response

Team chose [`response.CannotReproduce`]

- [x] I disagree

**Reason for disagreement:** The team managed to reproduce the bug in their screenshot. Observe how the link points to the respective file in AB3 and not in their repository.

<catcher-end-of-segment><hr>
## :question: Issue severity

Team chose [`severity.VeryLow`]
Originally [`severity.Medium`]

- [x] I disagree

**Reason for disagreement:** As stated in the original report: `Developers will be able to access the files with great difficulty by searching the actual repository for the files.`

<catcher-end-of-segment><hr>
